# Generated by Django 5.1.7 on 2025-04-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDjango', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='tarea',
            name='herramientas',
            field=models.ManyToManyField(related_name='herramientas', to='AppDjango.herramienta'),
        ),
    ]
