# Generated by Django 4.2.20 on 2025-04-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDjango', '0002_herramienta_tarea_herramientas'),
    ]

    operations = [
        migrations.AddField(
            model_name='herramienta',
            name='horas_disponibilidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('abierta', 'Abierta'), ('asignada', 'Asignada'), ('en_proceso', 'En proceso'), ('finalizada', 'Finalizada')], default='abierta', max_length=20),
        ),
        migrations.AddField(
            model_name='tarea',
            name='notas',
            field=models.TextField(default=10, max_length=500),
            preserve_default=False,
        ),
    ]
