# Generated by Django 5.2 on 2025-04-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDjango', '0004_alter_proyecto_fecha_fin_alter_proyecto_fecha_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_fin',
            field=models.DateTimeField(verbose_name='Fecha fin'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_inicio',
            field=models.DateTimeField(verbose_name='Fecha inicio'),
        ),
    ]
