# Generated by Django 5.1.7 on 2025-05-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDjango', '0005_alter_proyecto_fecha_fin_alter_proyecto_fecha_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='disponibilidad',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('no_disponible', 'No Disponible'), ('baja', 'Baja Médica'), ('vacaciones', 'Vacaciones'), ('viaje', 'Viaje')], default='disponible', max_length=20),
        ),
        migrations.AddField(
            model_name='herramienta',
            name='caducidad_garantia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='herramienta',
            name='fecha_compra',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='herramienta',
            name='pertenencia',
            field=models.CharField(choices=[('it', 'IT'), ('rrhh', 'RRHH'), ('i+d', 'I+D'), ('produccion', 'Producción'), ('logistica', 'Logística'), ('finanzas', 'Finanzas'), ('planificacion', 'Planificación'), ('pintura', 'Pintura'), ('otro', 'Otro')], default='otro', max_length=20),
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
